modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
#issueTrackerURL="https://github.com/ModernGamingWorlds-Mods/WoodenUtilities/issues"

[[mods]] #mandatory
modId="woodenutilities"
version="1.0"
displayName="Wooden Utilities"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wooden-utilities"
credits=""
authors="NovaMachina, LazynessMind, Serilum"
description="A Mod that adds wooden buckets and other wooden utilities to the game."